# Must be a double value: Radius in blocks
range: 50.0
# Must be an integer value: Duration in ticks
duration: 400
# Must be a boolean value: Allow effects higher than II
combine: false
# Must be a boolean value: Whether to apply default effects on empty beacons with tier >= 4
useDefault: true
# Must be strings: Default effects in case useDefault is true
defaultPrim: NIGHT_VISION
defaultSec: SATURATION
# Must be boolean: Whether to use the super star for transmitting stored effects
useSuperStar: false